spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 559633169013-656ckm1o687i3s1e1a8vhh3l9i9to78n.apps.googleusercontent.com
            clientSecret: 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
            scope: openid,profile,email,https://www.googleapis.com/auth/youtube

logging:
  level:
    com.com.googleIntegration: DEBUG
    org.springframework.security: TRACE
    org.springframework.security.oauth2: TRACE
    org.springframework.web: TRACE
    org.springframework.web.reactive: TRACE
